// This file has been autogenerated from a class added in the UI designer.

using System;
using System.ComponentModel;
using App2.Models;
using App2.ViewModels;
using Extra.iOS.Native.Commons;
using Foundation;
using GalaSoft.MvvmLight.Views;
using Services;
using UIKit;

namespace Extra.iOS.Native
{
	public partial class DetailsViewController : BaseViewController<DetailsViewModel>
	{
		public DetailsViewController (IntPtr handle) : base (handle)
		{
		}

	    public override void ViewWillAppear(bool animated)
	    {
	        base.ViewWillAppear(animated);     
            this.DetailsTableView.DataSource = new DataSource<Comment>( ViewModel.Items, DetailsTableView, "DetailsViewCell");
            
	    }
	}

}
