// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using Services;
using UIKit;

namespace Extra.iOS.Native
{
	public partial class DetailsViewCell : UITableViewCell, ICellBinding<Comment>
    {
		public DetailsViewCell (IntPtr handle) : base (handle)
		{
		}

        public void BindCell(Comment item)
        {
            TitelLabel.Text = item.Name;
        }
    }
}
