// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using GalaSoft.MvvmLight.Views;
using UIKit;

namespace Extra.iOS.Native
{
	public partial class MainNavigationViewController : UINavigationController
	{
		public MainNavigationViewController (IntPtr handle) : base (handle)
		{
		}

	    public override void ViewWillAppear(bool animated)
	    {
	        base.ViewWillAppear(animated);
	        var iosNavService = Application.Locator.NavigationService as NavigationService;
	        if (iosNavService == null)
	        {
	           throw new ApplicationException("sistema di navigazione non campatibile");
	        }
	        else
	        {
	            iosNavService.Initialize(this);
	        }
	    }

	    

          
	}
}
