// This file has been autogenerated from a class added in the UI designer.

using System;
using App2.ViewModels;
using Extra.iOS.Native.Commons;
using Foundation;
using UIKit;

namespace Extra.iOS.Native
{
	public partial class MainViewController : BaseViewController<HomeViewModel>
	{
        
		public MainViewController (IntPtr handle) : base (handle)
		{
			
		}

		public override void ViewWillAppear(bool animated)
		{
            PostTableView.DataSource = new DataSource<PostItemViewModel>(ViewModel.Items, PostTableView, "MainTableViewCell");
            PostTableView.Delegate = new PostTableViewDelegate(ViewModel);
            base.ViewWillAppear(animated);


			
        }


        public class PostTableViewDelegate: UITableViewDelegate
        {
            private HomeViewModel _homeViewModel;
            public PostTableViewDelegate(HomeViewModel homeViewModel)
            {
                _homeViewModel = homeViewModel;
            }
            public override void RowSelected(UITableView tableView, NSIndexPath indexPath)
            {
                var post = _homeViewModel.Items[indexPath.Row].InnertItem;
                _homeViewModel.NavigateToItemDetails(post);
            }
        }
	}
}
