// This file has been autogenerated from a class added in the UI designer.

using System;
using App2.ViewModels;
using Foundation;
using UIKit;

namespace Extra.iOS.Native
{
	public partial class MainTableViewCell : UITableViewCell, ICellBinding<PostItemViewModel>
	{
		public MainTableViewCell (IntPtr handle) : base (handle)
		{
		}

	    public void BindCell(PostItemViewModel item)
	    {
            TitleLabel.Text = item.Title;
            SubTitle.Text = item.Abstract;
        }
	}
}
